name             'dev-box'
maintainer       'Jakob Hilden'
maintainer_email 'jakobhilden@gmail.com'
license          'All rights reserved'
description      'Installs/Configures dev-box'
long_description 'Installs/Configures dev-box'
version          '0.1.0'

depends 'zshell'
depends 'sublime-text'
depends 'git'
depends 'rvm'
depends 'redisio'
depends 'java'
depends 'apt'
depends 'postgresql'
